const initialData = [
  {
    id: "UX001",
    status: "Pending",
    currency: "USD",
    senderAddress: {
      street: "123 Main St",
      city: "Tbilisi",
      postCode: "52000",
      country: "Georgia",
    },
    clientAddress: {
      street: "Cumhuriyet mahallesi Erses bloklari c blok kat 5",
      city: "Tbilisi",
      postCode: "5200",
      country: "Turkey",
    },
    clientName: "Mithat Ercan",
    clientEmail: "mithat552@gmail.com",
    invoiceDate: "2022-01-01",
    paymentDue: "2022-01-01",
    description: "This is a product that we are loving",
    items: [
      {
        name: "Mackbook Pro",
        quantity: 2,
        price: 3000,
      },
    ],
  },
  {
    id: "UX002",
    status: "Pending",
    currency: "GBP",
    senderAddress: {
      street: "123 Main St",
      city: "Tbilisi",
      postCode: "52000",
      country: "Georgia",
    },
    clientAddress: {
      street: "123 Main St",
      city: "Tbilisi",
      postCode: "5200",
      country: "Turkey",
    },
    clientName: "Serhat Ercan",
    clientEmail: "serhat@serhatercan.com",
    invoiceDate: "2022-01-01",
    paymentDue: "2022-01-01",
    description: "This is a product that we are loving",
    items: [
      {
        name: "Mackbook Pro",
        quantity: 1,
        price: 300000,
      },
      {
        name: "Airpods Pro 2",
        quantity: 3,
        price: 500,
      },
    ],
  },
  {
    id: "UX003",
    status: "Paid",
    currency: "GBP",
    senderAddress: {
      street: "123 Main St",
      city: "Tbilisi",
      postCode: "52000",
      country: "Georgia",
    },
    clientAddress: {
      street: "123 Main St",
      city: "Tbilisi",
      postCode: "5200",
      country: "Turkey",
    },
    clientName: "Serhat Ercan",
    clientEmail: "serhat@serhatercan.com",
    invoiceDate: "2022-01-01",
    paymentDue: "2022-01-01",
    description: "This is a product that we are loving",
    items: [
      {
        name: "Mackbook Pro",
        quantity: 1,
        price: 300000,
      },
      {
        name: "Airpods Pro 2",
        quantity: 3,
        price: 500,
      },
    ],
  },
  {
    id: "UX004",
    status: "Paid",
    currency: "GBP",
    senderAddress: {
      street: "123 Main St",
      city: "Tbilisi",
      postCode: "52000",
      country: "Georgia",
    },
    clientAddress: {
      street: "123 Main St",
      city: "Tbilisi",
      postCode: "5200",
      country: "Turkey",
    },
    clientName: "Serhat Ercan",
    clientEmail: "serhat@serhatercan.com",
    invoiceDate: "2022-01-01",
    paymentDue: "2022-01-01",
    description: "This is a product that we are loving",
    items: [
      {
        name: "Mackbook Pro",
        quantity: 1,
        price: 300000,
      },
      {
        name: "Airpods Pro 2",
        quantity: 3,
        price: 500,
      },
    ],
  },
  {
    id: "UX0005",
    status: "Paid",
    currency: "GBP",
    senderAddress: {
      street: "123 Main St",
      city: "Tbilisi",
      postCode: "52000",
      country: "Georgia",
    },
    clientAddress: {
      street: "123 Main St",
      city: "Tbilisi",
      postCode: "5200",
      country: "Turkey",
    },
    clientName: "Serhat Ercan",
    clientEmail: "serhat@serhatercan.com",
    invoiceDate: "2022-01-01",
    paymentDue: "2022-01-01",
    description: "This is a product that we are loving",
    items: [
      {
        name: "Mackbook Pro",
        quantity: 1,
        price: 300000,
      },
      {
        name: "Airpods Pro 2",
        quantity: 3,
        price: 500,
      },
    ],
  },
  {
    id: "UX006",
    status: "Pending",
    currency: "GBP",
    senderAddress: {
      street: "123 Main St",
      city: "Tbilisi",
      postCode: "52000",
      country: "Georgia",
    },
    clientAddress: {
      street: "123 Main St",
      city: "Tbilisi",
      postCode: "5200",
      country: "Turkey",
    },
    clientName: "Serhat Ercan",
    clientEmail: "serhat@serhatercan.com",
    invoiceDate: "2022-01-01",
    paymentDue: "2022-01-01",
    description: "This is a product that we are loving",
    items: [
      {
        name: "Mackbook Pro",
        quantity: 1,
        price: 300000,
      },
      {
        name: "Airpods Pro 2",
        quantity: 3,
        price: 500,
      },
    ],
  },
  {
    id: "UX007",
    status: "Draft",
    currency: "GBP",
    senderAddress: {
      street: "123 Main St",
      city: "Tbilisi",
      postCode: "52000",
      country: "Georgia",
    },
    clientAddress: {
      street: "123 Main St",
      city: "Tbilisi",
      postCode: "5200",
      country: "Turkey",
    },
    clientName: "Serhat Ercan",
    clientEmail: "serhat@serhatercan.com",
    invoiceDate: "2022-01-01",
    paymentDue: "2022-01-01",
    description: "This is a product that we are loving",
    items: [
      {
        name: "Mackbook Pro",
        quantity: 1,
        price: 300000,
      },
      {
        name: "Airpods Pro 2",
        quantity: 3,
        price: 500,
      },
    ],
  },
  {
    id: "UX008",
    status: "Paid",
    currency: "GBP",
    senderAddress: {
      street: "123 Main St",
      city: "Tbilisi",
      postCode: "52000",
      country: "Georgia",
    },
    clientAddress: {
      street: "123 Main St",
      city: "Tbilisi",
      postCode: "5200",
      country: "Turkey",
    },
    clientName: "Serhat Ercan",
    clientEmail: "serhat@serhatercan.com",
    invoiceDate: "2022-01-01",
    paymentDue: "2022-01-01",
    description: "This is a product that we are loving",
    items: [
      {
        name: "Mackbook Pro",
        quantity: 1,
        price: 300000,
      },
      {
        name: "Airpods Pro 2",
        quantity: 3,
        price: 500,
      },
      {
        name: "PS5",
        quantity: 1,
        price: 1200,
      },
      {
        name: "LG TV",
        quantity: 1,
        price: 1350,
      },
    ],
  },
];

export default initialData;
