const initialData = [
  {
    id: "UX001",
    status: "Pending",
    currency: "USD",
    senderAddress: {
      street: "123 Main St",
      city: "Tbilisi",
      postCode: "52000",
      country: "Georgia",
    },
    clientAddress: {
      street: "Cumhuriyet mahallesi Erses bloklari c blok kat 5",
      city: "Tbilisi",
      postCode: "5200",
      country: "Turkey",
    },
    clientName: "Mithat Ercan",
    clientEmail: "mithat552@gmail.com",
    invoiceDate: "2022-01-01",
    paymentDue: "2022-01-01",
    description: "This is a product that we are loving",
    items: [
      {
        id: "213HSQK",
        name: "Mackbook Pro",
        quantity: 2,
        price: 3000,
      },
    ],
  },
  {
    id: "UX002",
    status: "Pending",
    currency: "GBP",
    senderAddress: {
      street: "123 Main St",
      city: "Tbilisi",
      postCode: "52000",
      country: "Georgia",
    },
    clientAddress: {
      street: "123 Main St",
      city: "Tbilisi",
      postCode: "5200",
      country: "Turkey",
    },
    clientName: "Serhat Ercan",
    clientEmail: "serhat@serhatercan.com",
    invoiceDate: "2022-01-01",
    paymentDue: "2022-01-01",
    description: "This is a product that we are loving",
    items: [
      {
        id: "1123LKHJ",
        name: "Mackbook Pro",
        quantity: 1,
        price: 300000,
      },
      {
        id: "2ALK23NL",
        name: "Airpods Pro 2",
        quantity: 3,
        price: 500,
      },
    ],
  },
  {
    id: "UX003",
    status: "Paid",
    currency: "GBP",
    senderAddress: {
      street: "123 Main St",
      city: "Tbilisi",
      postCode: "52000",
      country: "Georgia",
    },
    clientAddress: {
      street: "123 Main St",
      city: "Tbilisi",
      postCode: "5200",
      country: "Turkey",
    },
    clientName: "Serhat Ercan",
    clientEmail: "serhat@serhatercan.com",
    invoiceDate: "2022-01-01",
    paymentDue: "2022-01-01",
    description: "This is a product that we are loving",
    items: [
      {
        id: "1231HLK",
        name: "Mackbook Pro",
        quantity: 1,
        price: 300000,
      },
      {
        id: "12JK3H1KJ3H",
        name: "Airpods Pro 2",
        quantity: 3,
        price: 500,
      },
    ],
  },
  {
    id: "UX004",
    status: "Paid",
    currency: "GBP",
    senderAddress: {
      street: "123 Main St",
      city: "Tbilisi",
      postCode: "52000",
      country: "Georgia",
    },
    clientAddress: {
      street: "123 Main St",
      city: "Tbilisi",
      postCode: "5200",
      country: "Turkey",
    },
    clientName: "Serhat Ercan",
    clientEmail: "serhat@serhatercan.com",
    invoiceDate: "2022-01-01",
    paymentDue: "2022-01-01",
    description: "This is a product that we are loving",
    items: [
      {
        id: "0912JHSD",
        name: "Mackbook Pro",
        quantity: 1,
        price: 300000,
      },
      {
        id: "1KJH313",
        name: "Airpods Pro 2",
        quantity: 3,
        price: 500,
      },
    ],
  },
  {
    id: "UX0005",
    status: "Paid",
    currency: "GBP",
    senderAddress: {
      street: "123 Main St",
      city: "Tbilisi",
      postCode: "52000",
      country: "Georgia",
    },
    clientAddress: {
      street: "123 Main St",
      city: "Tbilisi",
      postCode: "5200",
      country: "Turkey",
    },
    clientName: "Serhat Ercan",
    clientEmail: "serhat@serhatercan.com",
    invoiceDate: "2022-01-01",
    paymentDue: "2022-01-01",
    description: "This is a product that we are loving",
    items: [
      {
        id: "12JKG3JKRF",
        name: "Mackbook Pro",
        quantity: 1,
        price: 300000,
      },
      {
        id: "3984HWDF",
        name: "Airpods Pro 2",
        quantity: 3,
        price: 500,
      },
    ],
  },
  {
    id: "UX006",
    status: "Pending",
    currency: "GBP",
    senderAddress: {
      street: "123 Main St",
      city: "Tbilisi",
      postCode: "52000",
      country: "Georgia",
    },
    clientAddress: {
      street: "123 Main St",
      city: "Tbilisi",
      postCode: "5200",
      country: "Turkey",
    },
    clientName: "Serhat Ercan",
    clientEmail: "serhat@serhatercan.com",
    invoiceDate: "2022-01-01",
    paymentDue: "2022-01-01",
    description: "This is a product that we are loving",
    items: [
      {
        id: "389ASUDI",
        name: "Mackbook Pro",
        quantity: 1,
        price: 300000,
      },
      {
        id: "9832IOHDA",
        name: "Airpods Pro 2",
        quantity: 3,
        price: 500,
      },
    ],
  },
  {
    id: "UX007",
    status: "Draft",
    currency: "GBP",
    senderAddress: {
      street: "123 Main St",
      city: "Tbilisi",
      postCode: "52000",
      country: "Georgia",
    },
    clientAddress: {
      street: "123 Main St",
      city: "Tbilisi",
      postCode: "5200",
      country: "Turkey",
    },
    clientName: "Serhat Ercan",
    clientEmail: "serhat@serhatercan.com",
    invoiceDate: "2022-01-01",
    paymentDue: "2022-01-01",
    description: "This is a product that we are loving",
    items: [
      {
        id: "10AS9D8AD",
        name: "Mackbook Pro",
        quantity: 1,
        price: 300000,
      },
      {
        id: "19083ASODI",
        name: "Airpods Pro 2",
        quantity: 3,
        price: 500,
      },
    ],
  },
  {
    id: "UX008",
    status: "Paid",
    currency: "GBP",
    senderAddress: {
      street: "123 Main St",
      city: "Tbilisi",
      postCode: "52000",
      country: "Georgia",
    },
    clientAddress: {
      street: "123 Main St",
      city: "Tbilisi",
      postCode: "5200",
      country: "Turkey",
    },
    clientName: "Serhat Ercan",
    clientEmail: "serhat@serhatercan.com",
    invoiceDate: "2022-01-01",
    paymentDue: "2022-01-01",
    description: "This is a product that we are loving",
    items: [
      {
        id: "1J2HEWDSA90U",
        name: "Mackbook Pro",
        quantity: 1,
        price: 300000,
      },
      {
        id: "32189DWJKSH",
        name: "Airpods Pro 2",
        quantity: 3,
        price: 500,
      },
      {
        id: "2398WDJSKHD",
        name: "PS5",
        quantity: 1,
        price: 1200,
      },
      {
        id: "IUYERW9UJD",
        name: "LG TV",
        quantity: 1,
        price: 1350,
      },
    ],
  },
];

export default initialData;
