@startjson
{
  "id" : "",
  "senderAddress": {
    "street": "",
    "city": "",
    "postCode": "",
    "country": ""
  },
  "clientAddress": {
    "street": "",
    "city": "",
    "postCode": "",
    "country": ""
  },
  "clientName": "",
  "clientEmail": "",
  "createdAt": "",
  "currency": "dollar",
  "description": "",
  "items": [
    {
      "name": "",
      "quantity": "",
      "price": "",
      "total": ""
    }
  ]
}
@endjson